a= int(input("Enter firt number:"))
b= int(input("Enter second number:"))
print("A + B =", a+b,
        "\nA - B =",a-b,
        "\nA * B =", a*b,
        "\nA / B =", a/b ,
        "\nA**B =", a**b  ,
        "\nA//B =",a//b   ,
        "\nA%B =", a%b )