print ("WHAT IS YOUR NAME?")
name = input()
print ("HOW OLD ARE YOU?")
age = input()
print ("WHERE DO YOU LIVE?")
city = input()
print ("HELLO,", name)
print ("YOUR AGE IS", age)
print ("YOU LIVE IN", city)
end = input()