A = int(input('Please enter variable "A"\n\r'))
B = int(input('Please enter variable "B"\n\r'))

print('A + B =', A+B)
print('A - B =', A-B)
print('A * B =', A*B)
print('A / B =', A/B)
print('A ** B =', A**B)
print('A // B =', A//B)
print('A % B =', A%B)