a = float(input("Enter A: "))
b = float(input("Enter B: "))

print(f"A + B = {a + b}")
print(f"A - B = {a - b}")
print(f"A * B = {a * b}")
print(f"A / B = {a / b}")
print(f"A ** B = {a ** b}")
print(f"A // B = {a // b}")
print(f"A % B = {a % b}")