# Generated by Django 4.2 on 2023-05-29 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile_address_userprofile_citi"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="citi",
            new_name="city",
        ),
    ]
