# f = open('in/data')
# print(f.read())
# f.close()
# f = open('in/download.jpg', 'rb')
# print(f.read())
# f.close()
# f = open("out/out1.dat", "w")
# f.write("test10")
# # f.write("test20")
# # f.write("test30")
# # f.close()
# f = open("out/out1.dat", "a")
# f.write("test10")
# f.write("test20")
# f.write("test30")
# f.write("\n")
# f.close()
# with open("out/out1.dat", "a") as f:
#     f.write("test10")
#     f.write("test20")
#     f.write("test30")
#     f.write("\n")
