# Generated by Django 4.2 on 2023-04-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="product/%Y/%m/%d"),
        ),
    ]
