# Generated by Django 4.2 on 2023-05-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_product_available_alter_product_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.IntegerField(default=1, verbose_name="Вага"),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_unit",
            field=models.CharField(
                choices=[("kg", "кг"), ("g", "г"), ("thing", "шт")],
                default="кг",
                max_length=20,
                verbose_name="Одиниця виміру",
            ),
        ),
    ]
