# Generated by Django 4.2 on 2023-05-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_product_weight_product_weight_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_uk",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="available_en",
            field=models.BooleanField(default=True, verbose_name="Наявність"),
        ),
        migrations.AddField(
            model_name="product",
            name="available_ru",
            field=models.BooleanField(default=True, verbose_name="Наявність"),
        ),
        migrations.AddField(
            model_name="product",
            name="available_uk",
            field=models.BooleanField(default=True, verbose_name="Наявність"),
        ),
        migrations.AddField(
            model_name="product",
            name="created_en",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Створено"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_ru",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Створено"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_uk",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Створено"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Детальний опис"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Детальний опис"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_uk",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Детальний опис"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                db_index=True, max_length=150, null=True, verbose_name="Назва"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ru",
            field=models.CharField(
                db_index=True, max_length=150, null=True, verbose_name="Назва"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_uk",
            field=models.CharField(
                db_index=True, max_length=150, null=True, verbose_name="Назва"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_en",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="Ціна"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_ru",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="Ціна"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_uk",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="Ціна"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="uploaded_en",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Оновлено"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="uploaded_ru",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Оновлено"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="uploaded_uk",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Оновлено"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_en",
            field=models.IntegerField(default=1, null=True, verbose_name="Вага"),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_ru",
            field=models.IntegerField(default=1, null=True, verbose_name="Вага"),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_uk",
            field=models.IntegerField(default=1, null=True, verbose_name="Вага"),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_unit_en",
            field=models.CharField(
                choices=[("кг", "кг"), ("г", "г"), ("шт", "шт")],
                default="кг",
                max_length=20,
                null=True,
                verbose_name="Одиниця виміру",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_unit_ru",
            field=models.CharField(
                choices=[("кг", "кг"), ("г", "г"), ("шт", "шт")],
                default="кг",
                max_length=20,
                null=True,
                verbose_name="Одиниця виміру",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_unit_uk",
            field=models.CharField(
                choices=[("кг", "кг"), ("г", "г"), ("шт", "шт")],
                default="кг",
                max_length=20,
                null=True,
                verbose_name="Одиниця виміру",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight_unit",
            field=models.CharField(
                choices=[("кг", "кг"), ("г", "г"), ("шт", "шт")],
                default="кг",
                max_length=20,
                verbose_name="Одиниця виміру",
            ),
        ),
    ]
