# Generated by Django 4.2 on 2023-05-14 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_category_name_en_category_name_ru_category_name_uk_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="available_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="available_ru",
        ),
        migrations.RemoveField(
            model_name="product",
            name="available_uk",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_ru",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_uk",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price_ru",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price_uk",
        ),
        migrations.RemoveField(
            model_name="product",
            name="uploaded_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="uploaded_ru",
        ),
        migrations.RemoveField(
            model_name="product",
            name="uploaded_uk",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight_ru",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight_uk",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight_unit_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight_unit_ru",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight_unit_uk",
        ),
    ]
