# Generated by Django 4.2 on 2023-05-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_remove_product_available_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="weight_unit",
            field=models.CharField(
                choices=[("kg", "kg"), ("g", "g"), ("pcs", "pcs")],
                default="kg",
                max_length=20,
                verbose_name="Одиниця виміру",
            ),
        ),
    ]
