# Generated by Django 4.2 on 2023-05-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_alter_product_weight_unit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name",),
                "verbose_name": "product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True, verbose_name="available"),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_ru",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_uk",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="product/%Y/%m/%d", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=150, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                db_index=True, max_length=150, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(
                db_index=True, max_length=150, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_uk",
            field=models.CharField(
                db_index=True, max_length=150, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.CharField(
                db_index=True, max_length=150, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="uploaded",
            field=models.DateTimeField(auto_now=True, verbose_name="uploaded"),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.IntegerField(default=1, verbose_name="weight"),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight_unit",
            field=models.CharField(
                choices=[("kg", "kg"), ("g", "g"), ("pcs", "pcs")],
                default="kg",
                max_length=20,
                verbose_name="weight_unit",
            ),
        ),
    ]
