# Generated by Django 4.2 on 2023-05-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
