# Generated by Django 4.2 on 2023-05-27 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_customer_type_order_user_alter_order_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="weight_unit",
        ),
    ]
