# Generated by Django 4.2 on 2023-05-28 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_remove_orderitem_weight_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Phone number must be entered in the format: "+380.........". Up to 15 digits allowed.',
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
