# Generated by Django 4.2 on 2023-05-28 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_order_customer_type_alter_order_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer_type",
        ),
    ]
